### ISSUE TITLE
I have a question about Vjoy that I would like to ask you. Would it be convenient for you?

### ISSUE THREAD

**Issue by JunpengZhang** [FiendChain/VirtualJoystickCpp#1]
Do you understand the methods of silent devices?

**Comment by williamyang98** [comment]
Unfortunately I haven't used any parts of the api dealing with silent devices. I also can't seem to find any references to silent devices in the source code at [njz3/vJoy](https://github.com/njz3/vJoy/) aside from [here](https://github.com/njz3/vJoy/blob/d56de94a80d931d0b14f10cd676213b38f18d972/install/vJoyInstallerSigned.iss#L215). There are a few references to "quiet" in the source code but I'm not really sure what they mean. Hope you can figure this out.
